name: tp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: any
<<<<<<< Updated upstream
  shared_preferences: any 
=======
  shared_preferences: any

>>>>>>> Stashed changes
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_signin_button: ^1.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-LightItalic.ttf
          weight: 700
          style: italic
    - family: Samantha
      fonts:
        - asset: fonts/Samantha.ttf
        

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/rutas.png
    - assets/calcular_tiempo.png
    - assets/calificar_servicio.png
    - assets/denunciar.png
    - assets/felicitar.png
    - assets/logo.png
    - assets/calcula.jpeg
    - assets/recuperar.png
    - assets/denunciar1.png
    - assets/felicitar1.png
    - assets/rutas_mapa.PNG
    - assets/rutasFav.jpeg
  